
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.3-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install --upgrade pip setuptools
            pip install dbt

            mkdir -p ~/.dbt
            cp integration_tests/ci/profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Postgres"
          environment:
            POSTGRES_TEST_HOST: localhost
            POSTGRES_TEST_USER: root
            POSTGRES_TEST_PASS: ''
            POSTGRES_TEST_PORT: 5432
            POSTGRES_TEST_DBNAME: circle_test
          command: |
            . venv/bin/activate
            cd integration_tests
            dbt --warn-error deps --target postgres
            dbt --warn-error seed --target postgres --full-refresh
            dbt --warn-error compile --target postgres
            dbt --warn-error run --target postgres
            dbt --warn-error test --target postgres

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"